name: '✨ Feature Request'
description: Suggest a new feature or enhancement.
labels:
  - enhancement
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement! Please search [existing issues](./issues) to avoid duplicates.

  - type: markdown
    attributes:
      value: "⚠️👆 Please read the instructions above before submitting the issue 👆⚠️"

  - type: textarea
    id: description
    attributes:
      label: 'Describe the feature or enhancement'
      description: Provide a clear and concise description of the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 'Problem or use-case'
      description: Explain what problem this feature would solve or what use-case it would support.
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: 'Proposed solution or API design'
      description: Describe how you think this feature should work, or suggest an API/design if applicable.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 'Alternatives considered'
      description: Have you considered other approaches or workarounds?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context'
      description: Add any other context, links, or screenshots that help clarify the request.
    validations:
      required: false
