name: Publish
on:
  push:
    tags: ["*"]
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # PUBLICANDO EM NPM
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '>=20'
          registry-url: https://registry.npmjs.org/
          scope: "@heliomarpm"

      - name: Install Dependencies
        run: npm ci

      - name: Test & Build
        run: |
          npm run test
          npm run build

      - name: Publish NPM Package
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


      # PUBLICANDO EM GITHUB PACKAGE
      - name: Setup Node GPR
        uses: actions/setup-node@v4
        with:
          node-version: '>=20'
          registry-url: https://npm.pkg.github.com/
          scope: "@heliomarpm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish GPR
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # # ISSO PUBLICOU NO NPM
      # - name: Publish Lib
      #   uses: JS-DevTools/npm-publish@v3
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     strategy: all

